# Homebrew formula for mailroom.
# Install locally: brew install --formula ./formula/mailroom.rb
#
# To regenerate resource blocks with correct sha256 values:
#   pip install homebrew-pypi-poet
#   pip install mailroom[mcp]   # or: pip install -e ".[mcp]"
#   poet mailroom
#
# Then paste the output into this file, replacing the resource blocks below.

class Mailroom < Formula
  include Language::Python::Virtualenv

  desc "Email toolkit for AI assistants and command-line scripting"
  homepage "https://github.com/SmartLayer/mailroom"
  url "https://github.com/SmartLayer/mailroom/archive/refs/tags/v1.0.0.tar.gz"
  # sha256 — fill after tagging v1.0.0:
  #   curl -sL https://github.com/SmartLayer/mailroom/archive/refs/tags/v1.0.0.tar.gz | shasum -a 256
  sha256 "PLACEHOLDER"
  license "MIT"

  depends_on "python@3.13"

  # -- resource blocks generated by: poet mailroom --
  # Run the poet command above and paste output here.
  # Each transitive dependency needs a resource block with url + sha256.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "Email toolkit", shell_output("#{bin}/mailroom --help")
  end
end
